services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: user-db
    environment:
      SA_PASSWORD: "Your!StrongP@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    # Tắt healthcheck
    healthcheck:
      disable: true

  api:
    build:
      context: .                        
      dockerfile: UserService.API/Dockerfile
    container_name: user-api
    depends_on:
      db:
        condition: service_started
    environment:
      ConnectionStrings__DefaultConnection: > 
        Server=db;
        Database=UserDb;
        User Id=sa;
        Password=Your!StrongP@ssw0rd;
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "5000:80"
    restart: on-failure
